server:
  port: 8888

spring:
  application:
    name: config-server
  main:
    allow-bean-definition-overriding: true
  config:
    import: vault://
  cloud:
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: ${VAULT_SCHEME:http}
      uri: ${VAULT_SCHEME:http}://${VAULT_HOST:localhost}:${VAULT_PORT:8200}
      token: ${VAULT_TOKEN:hvs.VSlxeCypMevB7HLAYZ1hB73L}
    config:
      server:
        git:
          uri: https://${configServerHost:github.com/guilhermejr/repositorio-cofiguracao-sistema-dev}
          search-paths: '{application}'
  boot:
    admin:
      client:
        url: ${monitoramentoHost}
        username: ${monitoramentoUser}
        password: ${monitoramentoPass}
        instance:
          metadata:
            user:
              name: ${actuatorUser}
              password: ${actuatorPass}

sistema:
  eureka:
    host: ${eurekaServerHost}
    login: ${eurekaServerUser}
    senha: ${eurekaServerPass}
  config:
    login: ${configServerUser}
    senha: ${configServerPass}

eureka:
  client:
    service-url:
      defaultZone: 'http://${sistema.eureka.login}:${sistema.eureka.senha}@${sistema.eureka.host}:8761/eureka'
  instance:
    hostname: 'config-server'


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@